# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(662, 302)
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setGeometry(QtCore.QRect(440, 270, 193, 28))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 20, 271, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.protein_chooser_1 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.protein_chooser_1.setObjectName("protein_chooser_1")
        self.verticalLayout.addWidget(self.protein_chooser_1)
        self.ligand_chooser_1 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.ligand_chooser_1.setObjectName("ligand_chooser_1")
        self.verticalLayout.addWidget(self.ligand_chooser_1)
        self.mode_chooser = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.mode_chooser.setObjectName("mode_chooser")
        self.verticalLayout.addWidget(self.mode_chooser)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(170, 140, 271, 118))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.protein_chooser_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.protein_chooser_2.setObjectName("protein_chooser_2")
        self.verticalLayout_2.addWidget(self.protein_chooser_2)
        self.smile_chooser_2 = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_2)
        self.smile_chooser_2.setObjectName("smile_chooser_2")
        self.verticalLayout_2.addWidget(self.smile_chooser_2)
        self.output_chooser = QtWidgets.QTextEdit(Form)
        self.output_chooser.setGeometry(QtCore.QRect(460, 20, 151, 91))
        self.output_chooser.setObjectName("output_chooser")
        self.mode_chooser_2 = QtWidgets.QComboBox(Form)
        self.mode_chooser_2.setGeometry(QtCore.QRect(40, 140, 73, 22))
        self.mode_chooser_2.setObjectName("mode_chooser_2")
        self.output_chooser_2 = QtWidgets.QTextEdit(Form)
        self.output_chooser_2.setGeometry(QtCore.QRect(460, 140, 151, 111))
        self.output_chooser_2.setObjectName("output_chooser_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
