services:
  pymol-fitter:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: hitesit/pymol-fitter
    container_name: pymol-fitter
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s