services:
  pymol-fitter:
    build:
      context: ..
      dockerfile: docker/Dockerfile.cpu
    image: hitesit/pymol-fitter:latest
    container_name: pymol-fitter
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - GUNICORN_TIMEOUT=1200  # 20 minutes
    profiles:
      - cpu
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # GPU-enabled version as a separate service
  pymol-fitter-gpu:
    build:
      context: ..
      dockerfile: docker/Dockerfile.gpu
    image: hitesit/pymol-fitter:gpu
    container_name: pymol-fitter-gpu
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - GUNICORN_TIMEOUT=1200  # 20 minutes
    profiles:
      - gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s